baseURL = 'https://jeffreygroneberg.github.io'
languageCode = 'en-us'
title = 'Jeff @ retr0.party'
theme = "terminal"

[Permalinks]
    post = "/:filename/"

[params]
  contentTypeName = "posts"
  themeColor = "blue"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true
  description = "My name is Jeff and this is my personal small minimalistic blog"
  headline = "A page about retrogaming, tech and software"
  shareTwitter = true
  opengraph = true
  dateFormat = "Mon, Jan 2, 2006"

  [languages]
  [languages.en]
    title = "Jeffs retr0.party"
    subtitle = "My small minimalistic blog"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Jeff's retr0.party"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/pages/about"
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/posts"
